name: go code scanner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  code-scan:
    name: GoKart scanner
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: run GoKart
      uses: kitabisa/gokart-action@v1.0.0
      with:
        globalsTainted: true
    - name: Upload results
      uses: github/codeql-action/upload-sarif@v3
